// tools/build-fonts.js
// Reads the curated .flf fonts in assets/flf/ and emits js/figlet-fonts.js,
// which exposes the raw font data to the browser (so the app renders real
// FIGlet fonts offline from file://, with no fetch/fs at runtime).
//
//   node tools/build-fonts.js
//
// Output shape (js/figlet-fonts.js):
//   window.FIGLET_FONTS = {
//     "ansishadow": { name: "ANSI Shadow", label: "ANSI Shadow", data: "<flf text>" },
//     ...
//   };
//   window.FIGLET_FONT_ORDER = ["ansishadow", ...];
//
// `name` is the key passed to figlet.parseFont/textSync; `label` is shown in
// the settings panel; `key` (the object key) is the `afont-<key>` style id.

const fs = require('fs');
const path = require('path');
const figlet = require('../js/figlet.js');

const repoRoot = path.resolve(__dirname, '..');
const flfDir = path.join(repoRoot, 'assets', 'flf');
const outFile = path.join(repoRoot, 'js', 'figlet-fonts.js');

// Curated order (ANSI Shadow first — the user's priority font). Each entry is a
// .flf filename (without extension) present in assets/flf/.
const ORDER = [
  'ANSI Shadow', 'ANSI Regular', 'Standard', 'Big', 'Banner', 'Slant', 'Small', 'Mini',
  'Doom', 'Digital', 'Bulbhead', 'Block', '3D-ASCII', 'Larry 3D', 'Colossal', 'DOS Rebel',
  'Delta Corps Priest 1', 'THIS', 'Acrobatic', 'Avatar', 'Bloody', 'Crawford', 'Cyberlarge',
  'Cybermedium', 'Fender', 'Ghost', 'Graffiti', 'Isometric1', 'Sub-Zero', 'Star Wars',
  'Speed', 'Stop', 'Univers', 'Calvin S', 'Electronic', 'Shadow',
  // User-requested additions
  'Classy', 'Coder Mini', 'BlurVision ASCII', 'Mono 12', 'Rebel', 'Elite', 'Bolger', 'AMC AAA01',
];

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

const fonts = {};
const order = [];
const seen = {};

ORDER.forEach((name) => {
  const file = path.join(flfDir, name + '.flf');
  if (!fs.existsSync(file)) {
    console.error('SKIP (missing file): ' + name);
    return;
  }
  const data = fs.readFileSync(file, 'utf8');
  // Validate the font parses AND has real digit + colon glyphs. Many display
  // .flf files define letters only (digit positions are blank), which would
  // make the clock show nothing where the time should be — those are unusable
  // here and get dropped.
  try {
    figlet.parseFont(name, data);
    var required = '0123456789:'.split('');
    var missing = required.filter(function (ch) {
      var art = figlet.textSync(ch, { font: name, width: 100000, whitespaceBreak: false });
      return !art || !art.replace(/\s/g, '').length;
    });
    if (missing.length) {
      console.error('DROP (no glyphs for ' + JSON.stringify(missing.join('')) + '): ' + name);
      return;
    }
  } catch (e) {
    console.error('SKIP (render error): ' + name + ' -> ' + e.message);
    return;
  }
  const key = slug(name);
  if (seen[key]) {
    console.error('SKIP (duplicate key ' + key + '): ' + name);
    return;
  }
  seen[key] = true;
  fonts[key] = { name: name, label: name, data: data };
  order.push(key);
});

const banner = '// Generated by tools/build-fonts.js — do not edit by hand.\n' +
  '// Raw FIGlet (.flf) font data embedded for offline rendering.\n';
const body =
  banner +
  'window.FIGLET_FONTS = ' + JSON.stringify(fonts) + ';\n' +
  'window.FIGLET_FONT_ORDER = ' + JSON.stringify(order) + ';\n';

fs.writeFileSync(outFile, body);
console.log('Wrote ' + outFile + ' with ' + order.length + ' fonts (' +
  Math.round(body.length / 1024) + ' KB).');
console.log('Order: ' + order.join(', '));
